### ISSUE TITLE
Django Admin: Allow Staff level users to see "User domain roles"

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1291]
### Issue description

Usability testing revealed that analysts will need access to the “User Domain Roles” section, which is currently available only to "full-access" users, so that they may look up relationships between managers and domains:

1. all managers for a particular domain and 
2. all domains managed by a particular manager

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/b9f54a2e-de9a-4657-bc1a-2b5cb96c943e)

### Acceptance criteria

- [ ] "cisa-analyst" users can see and use the "User domain roles" model.
- [ ] "cisa-analyst" users can "delete" a user domain role.

### Additional context

[Miro Research board](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764569104364449)

### Links to other issues

Related to #1292 #1298 (Do together)

**Comment by Katherine-Osos** [comment]
@h-m-f-t Should analysts also be able to "Delete" a domain role? For example, in the use case described in this [slack thread](https://cisa-corp.slack.com/archives/C066ZBWFLRW/p1701463482798209), Alex would need to be able to view this section of the admin and have the ability to delete an entry. 

A little background: Currently there's only one role - Manager - to select, and the admin forces you to select a role in order to "Save" the entry. The only option for removing the role is to delete the entry altogether. 

cc: @neilmb and @abroddrick since you were part of that slack thread.

**Comment by abroddrick** [comment]
Agreed with being able to delete a domain role! @Katherine-Osos good catch!

**Comment by h-m-f-t** [comment]
Yep, agreed! Thanks @Katherine-Osos
