### ISSUE TITLE
Adding a duplicate email in "Domain managers" tab does not provide warning message

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1405]
### Current Behavior

Task: manage a domain

When adding a new user in the "Domain managers" tab, if one adds an email that is already listed, it doesn't give a warning that you are adding an email that is already there. Just display a successful message.

### Expected Behavior

Display a message to inform user that the email address is already listed.

### Steps to Reproduce

When adding a new user in the "Domain managers" tab, if one adds an email that is already listed, it doesn't give a warning that you are adding an email that is already there. Just display a successful message.

**Comment by abroddrick** [comment]
@Katherine-Osos would this require some content for a new warning message? Or think it's straight forward enough the dev can take a shot and the wording of the message can be refined during the design review?

**Comment by vickyszuchin** [comment]
Added "refinement" label because of the question posted in comment for @Katherine-Osos.

**Comment by Katherine-Osos** [comment]
@abroddrick There are two scenarios: 1) user invites someone who was already invited but has not logged in yet, i.e. they're still in the "invited" table. 2) user invites someone who is already a domain manager, i.e. they're in the "domain managers" table. 

For scenario 1, show this message: 
<email> has already been invited to this domain. 

For scenario 2, show this message: 
<email> is already a manager for this domain.


For design, use the warning status (yellow message bar) rather than success status (green message bar).
