### ISSUE TITLE
Investigate why "via" text shows in Gmail on emails sent by help@get.gov

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1451]
### Issue description

For those using Gmail or Google Workspace, it'd be nice to remove the "via" that appears. This is showing because we're something is off in the way our AWS SES is set up for email authentication (my guess is DKIM).

![image](https://github.com/cisagov/manage.get.gov/assets/603901/6d4ef539-55e6-415b-92ff-6626ead20be8)

Let's review Google's [support doc](https://support.google.com/mail/answer/1311182?hl=en&sjid=17996526686633301884-NA#null&zippy=:~:text=Remove%20%22via%22%20information%20from%20emails%20not%20sent%20through%20Gmail) and make any necessary changes.

### Acceptance criteria

- [ ] "via" no longer appears in Gmail when emails from help@get.gov are received

### Additional context

To diagnose the issue, It would be helpful to use https://www.learndmarc.com/ and send an email there from SES.

**Comment by katypies** [comment]
This is ready and I can investigate the specifics of our authentication records.

**Comment by katypies** [comment]
Everything is set up correctly for SPF, DKIM, and DMARC. The `via` only shows up when the following are true:

1. There's a link in the email that includes the protocol (for example, the link to Login.gov in our invitation emails; but references to `get.gov` or `manage.get.gov` or `Login.gov` on their own don't trigger this)
2. The Google account has a spam filter pre-processing the email (so most likely Google Workspace, and not regular Gmail, and likely not all Workspace accounts).

In the case of my Workspace account, login URL is changed by the spam filter pre-processing; additional headers are attached as well, and the header and body hashes no longer match what they were upon sending from SES.

**What's next?**

It's unlikely we can control that behavior for spam filters, but it's also _more_ likely our users/customers will have these kinds of filters in place since they're governments. Technically we're not failing DMARC, so emails aren't going to spam -- SPF alignment is fine, but the DKIM is showing as a failure and Google is surfacing that through the `via` text.

- We could make this friendlier by sending from a custom from domain. So, in the cases it shows up, it could say `help@get.gov via mail.get.gov` instead of the long AWS/SES domain. One trade-off here is that SES then wouldn't process bounces - we have to accept mail to the `mail from` domain, and process those.

- We currently are using strict mode for the DKIM alignment. I'm not confident without some testing, but there's a possibility that relaxed mode for DKIM alignment would fix this, too. 

@h-m-f-t - if you have an initial opinion on whether we should aim to solve this given the context above, let me know. Otherwise, we can also chat about the tradeoffs and additional testing.

**Comment by h-m-f-t** [comment]
Thanks, @katypies! Where does DKIM show as failing?

**Comment by katypies** [comment]
@h-m-f-t 

If you "View Original" for an email in Gmail/Google, Google will report the SPF and DKIM status.

Here's an email sent via SES that doesn't have a hyperlink modified by the spam filter (which passes both SPF and DKIM checks):

<img src="https://github.com/user-attachments/assets/f3b8518f-7d7d-4d9f-8e6d-9c9c07ec639c" height="75" />

And here's one that has the hyperlink that was filtered/modified before Google/Gmail received it (this email is one that shows `via`):

<img src="https://github.com/user-attachments/assets/2822c875-8643-4e19-b682-4f310b825655" height="75" />

**Comment by katypies** [comment]
We know (broadly) why this is happening. I'm going to look at gathering data on how much it might be happening with Google/Gmail, or other providers via our DMARC reporting. Then we can determine whether we need to take action, and if so, the relative impact.
