### ISSUE TITLE
Optimize Gunicorn gthread setup

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1770]
### Issue description

We recently switched to using gthread with only one worker as part of our gunicorn setup (see run.sh). However, the documentation references that there should be more than one worker, and in our case ideally 3 workers.

### Acceptance criteria

- [ ] update the gunicorn setup to have multiple workers (3 would be ideal unless dev determines otherwise)
- [ ] add a shared cache between the workers (otherwise errors will occur)

**Comment by zandercymatics** [comment]
General implementation note:

I would like to note that "workers", from the context of guincorn, are a set of _instances_ - rather than threads. _Threading_ is done automatically by the library. This distinction is due to how "threading" works in python with the GIL.
https://dev.to/lsena/gunicorn-worker-types-how-to-choose-the-right-one-4n2c

We already do instancing for load balancing purposes through cloud.gov, so that should be kept in mind as we start scaling this up.

![image](https://github.com/cisagov/manage.get.gov/assets/141044360/35ec18f7-cf3f-4439-b267-9ebc008202f8)
