### ISSUE TITLE
Dev: List all associated domains and requests for `contacts`

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2026]
### Issue description

As an analyst
I want to be able to view all the existing domains or requests associated with a particular contact
so that I can adjudicate requests much easier

### Acceptance criteria

- [ ]  implement Figma design (TBD link)
- [ ]  (Optional) Once completed, remove alerts that notify analysts with contact related objects as they would be unnecessary (implemented in PR https://github.com/cisagov/manage.get.gov/pull/1664)

### Links to other issues

- Blocked by: #1875

**Comment by vickyszuchin** [comment]
Moving ticket from "New" to "Backlog" because this ticket was split from a ticket that was previously triaged and accepted into the product backlog.

**Comment by abroddrick** [comment]
Refinement add as no contact can be linked to a domain. Do we mean domain information here?

**Comment by h-m-f-t** [comment]
I think the intent of this issue was for an analyst to know whether a SO or an "additional contact" was named on a different domain request or an existing domain I think this could be useful, but we also plan to solve this long-term with the org model. I propose we close this and #1875. What do you think, @katypies?

**Comment by katypies** [comment]
Agreed - Org Model and some other changes will better address the rationale for this.
