### ISSUE TITLE
Design: modifications needed for `domain request form` in org model

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2124]
### Issue description

PROBLEM:
The introduction of the org model to domain management in the registrar may require changes to the way domains are requested. Since new domains may **not** be requested by just any `Rando`, but rather must be requested by an authorized user within the organization, there may be some flow changes required to the request process.

SOLUTION:
Determine and document the design changes necessary for requesting a new domain within an organization.

### Acceptance criteria

- [x] determine what changes need to be made to the request form
- [x] create Figma designs 
- [ ] create dev tickets to support these design and flow changes

### Links to other issues

- EPIC: #1772 
- Blocked by: #2063 
- 🔄 similar to https://github.com/cisagov/manage.get.gov/issues/1635, which we closed in favor of this issue

**Comment by katypies** [comment]
This might be superceded by #2206 - noting to come back and confirm.

**Comment by katypies** [comment]
This one doesn't supercede #2206, but is better suited for the next sprint to identify additional changes for the flow.

**Comment by gabydisarli** [comment]
Shared for review:

- [Figma designs](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=5844-69614)
- [Figma prototype](https://www.figma.com/proto/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?page-id=5844%3A69614&node-id=5844-69619&viewport=922%2C1538%2C0.39&t=1jH6DtwBXvLyMPO7-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5844%3A69619&show-proto-sidebar=1)

**Comment by katypies** [comment]
@gabydisarli  these look great - I think you covered the part about suborg flow in the meeting yesterday, which looks like the major change (aside from some language removed later in the flow). The only feedback I have was mentioned in that meeting: Instead of having yes/no, @Katherine-Osos recommended re-phrasing the question, and then having the answers be more explicit like "Yes, this is for a sub-organization of <Org>." Or "No, this request is not for a sub-organization of Org." @Katherine-Osos  may want to specify that content. Otherwise, 👍  Approved to move forward here!

**Comment by gabydisarli** [comment]
[Prototype](https://www.figma.com/proto/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?page-id=5844%3A69614&node-id=5844-69619&viewport=922%2C1538%2C0.39&t=OV1IwWYrjDbAlcRS-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5844%3A69619&show-proto-sidebar=1)
[Figma designs](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7998-65087&t=xT6hsk2aYbd0uwY8-11)

Design approved 8/30 see [Slack thread](https://cisa-corp.slack.com/archives/C07589TAY57/p1724454693722229)
