### ISSUE TITLE
Tribal gov step in domain request wizard gets skipped (shows as locked)

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2322]
### Current Behavior

Tribal gov step in domain request wizard gets skipped (shows as locked) when it's the last unfilled step in an application you come to edit.

### Expected Behavior

Tribal gov step should not be locked when it is unfilled.

### Steps to Reproduce

1- Start an application
2- Select Tribal
3- Go to home page
4- Click edit on the application
5- See that Tribal Government has been skipped

### Environment

Stable
Staging

### Additional Context

Per Rachid: My guess is this is some bug in the logic that populates context for unlocked steps.

[Slack discussion](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1718068191072389)

### AC

- [ ] Solve this bug
- [ ] evaluate if any other conditional steps in our request flow are effected as well and ensure they are also fixed (break into a separate ticket if this balloons beyond the estimate for time to resolve)

**Comment by PaulKuykendall** [comment]
We need to evaluate the flow with other, non-tribal, steps to determine whether this bug can pop up elsewhere.

**Comment by abroddrick** [comment]
@PaulKuykendall let's just add that to the AC

**Comment by Matt-Spence** [comment]
Note: On further investigation is appears that the real problem is that the "Election Organization" step is showing as filled out, when it should be locked. This is giving the appearance that a step has been skipped when in fact none of them have been filled out. This applies to any conditionally available step before "Election Organization", such as Federal Branch Type.

**Comment by vickyszuchin** [comment]
Removed "research" label based on Matt's comment.
