### ISSUE TITLE
Portfolio view matches the figma for the Domains page and navigation

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2349]
### Issue description

As an Portfolio user (manager and admin),
I want to view and search my domains
So I can efficiently view my domain information

### Acceptance criteria

- [ ] User can view the Domains table [figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=3941-132915&t=9lLcDLKLOVzRRpWY-11) design document. Note some of the missing items below but more may be added:
- [x] navigation bar is changed to reflect the figma 
- [x] in the nav bar, the portfolio name is a clickable link that does nothing, but the value should be the organization name from the portfolio object)
- [x] The domain table shows suborganization ([Figma link](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=3941-132915&t=9lLcDLKLOVzRRpWY-11))
- [x] search reset has icon ([Figma link](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=4346-71424&t=9lLcDLKLOVzRRpWY-11)) 

### Links to other issues

- blocked by #2365

**Comment by abroddrick** [comment]
@gabydisarli 
This is the comment this was drawn from and [this is the link ](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=2906-26900&t=FOv0P4v7F1QBBEmE-11) but it takes me to a page that doesn't have the search or reset items so I think it's the wrong link. Mind grabbing the right link to the to the icon we need to show on the search bar instead of the current reset? (Link can be added to the last AC
![Image](https://github.com/cisagov/manage.get.gov/assets/109625347/c6d8137c-ca50-47e6-8f27-ece71fb93be8)

**Comment by vickyszuchin** [comment]
Thanks for bringing this up. I'm looking at the figma in which @abroddrick left the comment for this ticket and the design is allowing the edit-mode. So, do we want this ticket to cover the different scenarios?

1. Admin that is not a domain manager for any domains in portfolio (view-mode)
2. Admin that is a domain manager for a selection of domains in the portfolio (edit-mode)
