### ISSUE TITLE
Create and Organize Figma design system and working files

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2583]
### Issue description
Establish goals, align with the team on design system improvements and new processes.

### Acceptance criteria
- [x] Align with design team on goals and progress
- [x] Create and organize a stand alone design system from working Figma files. Create new tickets are needed.
- [x] Organize the designs for manage.get.gov and get.gov. Create new tickets as needed
- [x] List any issues created as apart of this work below.

### Additional context
The Figma file is out of date and doesn't always match what's in production. This leads to doubled efforts when designers have to make updates to a screen that hasn't been kept up to date in Figma. The Figma should have parity with what's in production so devs and designers know that the Figma is correct and can be trusted.

### Links to other issues
- Plan for design system improvements [#2584](https://github.com/cisagov/manage.get.gov/issues/2584)
- Figma component audit: manage.get.gov [#2582](https://github.com/cisagov/manage.get.gov/issues/2582)
- Figma component audit: get.gov [#2585](https://github.com/cisagov/manage.get.gov/issues/2585)

Links to files:

- [Figma Audit](https://docs.google.com/spreadsheets/d/1jWK1VMdK1zqLCbYN0Efp0rGNFMGJP-iKgQefplIUFUw/edit?usp=sharing)
- [High Level Overview ](https://docs.google.com/presentation/d/1Jzxv1Eq2jjCN6G4o2dF4PziShQai8oAq/edit#slide=id.p14)
- [Plan for design team](https://miro.com/app/board/uXjVKrdXqXs=/?moveToWidget=3458764598442800249&cot=14)
- [Link 1 for component update list](https://github.com/cisagov/manage.get.gov/issues/2585#issue-2466334837)
- [Link 2 for component update list](https://github.com/cisagov/manage.get.gov/issues/2582#issue-2466292336)
- [.Gov Figma Presentation](https://docs.google.com/presentation/d/1yPZ-LI8NyuKqHeCbeTWIwsB8V7uG_AKk/edit#slide=id.g2800fc961b4_0_973)
- New[ .Gov Design System](https://www.figma.com/design/G2HANRHy8pnlY5ENvmpKY8/.Gov-Design-System?m=auto&node-id=80-352&t=bPEgSmc1zJGo5wC8-1) Figma file  
- [Presentation on updates](https://docs.google.com/presentation/d/1yPZ-LI8NyuKqHeCbeTWIwsB8V7uG_AKk/edit?usp=sharing&ouid=102412567147253674869&rtpof=true&sd=true)

**Comment by joet333** [comment]
Starting to work on general roadmap/overview (WIP) and creating doc for audit (WIP).
Adding links to both in the story itself.

**Comment by joet333** [comment]
Testing component transfer with @AnnaGingle. Still working on best ways and what we want to do exactly. Shared out that things might be a little "funky" while we organize.

**Comment by joet333** [comment]
Have meeting with @AnnaGingle to start moving and organizing files on Friday.

**Comment by joet333** [comment]
@Katherine-Osos moved to this sprint since we are going to be working on organizing some things on Friday and we had some discussions today around organization ideas.

**Comment by joet333** [comment]
Updated to include links to main audit stories (and component updates stories)

**Comment by joet333** [comment]
@Katherine-Osos @AnnaGingle I updated this ticket to be more reflective of the next steps. I will also create another ticket for "Prioritizing component updates" please let me know if you have any questions.

**Comment by joet333** [comment]
I took advantage of you all being on holiday to transfer components from our working Figma file .[gov Design CISA](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?m=auto&node-id=2807-4669&t=wy11Uy41J3wlhMLT-1) (working file) to our new .[Gov Design System](https://www.figma.com/design/G2HANRHy8pnlY5ENvmpKY8/.Gov-Design-System?node-id=34-1358&t=tDBY1xlEpf4sbTrz-1) (design library) Figma file and for the most part it went pretty smoothly.
Component Transfer: All components have been moved to the new design library. I triple-checked that all links remained intact.
Org Model Components: I have left these in the working file, but they likely can be moved soon.
Prototypes: Please double-check your prototypes to ensure all selectable spots are still working.
Pagination Issues: I had to manually redo many pagination instances and updated variations.
Naming & Organization: Still in progress for the design library, but the remaining updates should be minor.
Separation of Files: The [get.gov base files](https://www.figma.com/design/qeWM03sfjXgHBHB23rsD6X/get.gov-base-pages?node-id=1057-5467&t=NSV9P1NVKSeuFOEN-1) are now separated from the working files.
Emoji Update: Emojis on titles of the working files have been reduced to help with cognitive overload.
If you notice anything off, let me know, and I’ll fix it ASAP. Looking forward to your feedback!
Otherwise, I hope this transfer makes life easier going forward and look out for more updates and information soon!

**Comment by joet333** [comment]
Still need to organize and get a few more components moved over in the Design Library.

**Comment by vickyszuchin** [comment]
Moving this "In-progress" sprint 52 ticket to newly started Sprint 53.

**Comment by joet333** [comment]
Create and organize a stand alone design system ([.gov Design System](https://www.figma.com/design/G2HANRHy8pnlY5ENvmpKY8/.Gov-Design-System?m=auto&node-id=80-352&t=bPEgSmc1zJGo5wC8-1)) from working Figma files. Create new tickets are needed.  
>> components moved, but organization and naming still needed 

Align with design team on goals and progress
>> [Presentation ](https://docs.google.com/presentation/d/1yPZ-LI8NyuKqHeCbeTWIwsB8V7uG_AKk/edit#slide=id.g2800fc961b4_0_973)started and share out to happen after work is complete.


No new tickets needed yet.

**Comment by joet333** [comment]
Updates made to .govDS figma file now reflect USWDS names where possible and organization has been completed. 

https://docs.google.com/document/d/1gLJGzRmRlXl8ohfL1BKbXKziVz6fmDZVMN-0TjoLznM/edit
^^ doc above lists all changes made. 
Next step will be to prioritize component audit updates.

**Comment by joet333** [comment]
Have a few updates to make to presentation from Katherine's review. Otherwise good to schedule presentation.

**Comment by joet333** [comment]
Updates have been made. Now just need to present. Marking as done. 
https://docs.google.com/presentation/d/1yPZ-LI8NyuKqHeCbeTWIwsB8V7uG_AKk/edit#slide=id.g28599b298ed_2_87
