### ISSUE TITLE
Re-run SO and agency scripts after fixing errors

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2715]
### Issue description

In #2588 and #2587, the senior official and federal agency update scripts were ran. The SO worked fine, but then federal agencies had over 50 federal agencies that couldn't be updated because they were missing values in the spreadsheet for these scripts. Of those only 13 were identified as actually incorrect and that they through an error because there were two names for the federal agency in stable. This spreadsheet dictates the duplicates

### Acceptance criteria

- [x] determine which duplicates need to be removed, and update stable accordingly. Update the senior official [spreadsheet](https://docs.google.com/spreadsheets/d/14oXHFpKyUXS5_mDWARPusghGdHCrP67jCleOknaSx38/edit?gid=479328070#gid=479328070) if needed. Product approval on which to remove is needed.
- [x] determine if so script needs to be re-run for these domains
- [x] rerun the federal agency update script (and the fill SO script if applicable) on stable or manually change the data as there are only 13 entries

### Additional context

note to run the script you need to be granted manager access to stable temporarily, please request this if needed. Also for running the script you would need to make sure to do this without downloading the file onto a personal device, you could do this with curl or using s3 (or just do this manually)

### Links to other issues

relates to #2588 
relates to #2399 
relates to #2587

**Comment by h-m-f-t** [comment]
I've updated the [duplicate](https://docs.google.com/spreadsheets/d/1Mylnt81qPDMBh6v-lXS-kTF6YM1_EWAgUVRMr3LzQws/edit?gid=1107322366#gid=1107322366) list.

**Comment by CocoByte** [comment]
A few of the federal agencies @h-m-f-t flagged for deletion in stable were associated with several objects (see image).  These objects were updated to point to equivalent federal agencies.  Changes were done manually in /admin as follows;

- Domain information: [ustda.gov](http://ustda.gov/) - United States Trade and Development Agency (original) --> (updated to) U.S. Trade and Development Agency
- Domain information: [usich.gov](http://usich.gov/) - United States Interagency Council on Homelessness (original)--> (updated to) U.S. Interagency Council on Homelessness
- Domain request: [psiccfireinfo.gov](http://psiccfireinfo.gov/) - Department of Agriculture (original) --> (updated to) U.S. Department of Agriculture
- Domain information: [ich.gov](http://ich.gov/) - United States Interagency Council on Homelessness (original) --> (updated to) U.S. Interagency Council on Homelessness
- Senior official: [Sanya Cade ](https://manage.get.gov/admin/registrar/seniorofficial/92/change/)- United States Interagency Council on Homelessness (original) --> (updated to) U.S. Interagency Council on Homelessness
- Senior official: [Angelia Vicchiollo - ](https://manage.get.gov/admin/registrar/seniorofficial/94/change/)United States Trade and Development Agency (original) --> (updated to) U.S. Trade and Development Agency

ORIGINAL ERROR MESSAGE:
![Image](https://github.com/user-attachments/assets/16f6f601-b703-45fa-b792-12b2daf1dae7)

**Comment by CocoByte** [comment]
After the above update, it was noted that the the senior official [spreadsheet](https://docs.google.com/spreadsheets/d/14oXHFpKyUXS5_mDWARPusghGdHCrP67jCleOknaSx38/edit?gid=479328070#gid=479328070) was already up-to-date with these federal agency changes.

The [federal agency update script](src/registrar/management/commands/populate_federal_agency_initials_and_fceb.py) was not run since the updates to the DB were done manually.

**Comment by CocoByte** [comment]
A few of the federal agencies @h-m-f-t flagged for deletion in stable were associated with several objects).  These objects were updated to point to equivalent federal agencies and then the flagged federal agencies were deleted.  Changes were done manually in /admin.

After this update, it was noted that the the senior official [spreadsheet](https://docs.google.com/spreadsheets/d/14oXHFpKyUXS5_mDWARPusghGdHCrP67jCleOknaSx38/edit?gid=479328070#gid=479328070) was already up-to-date with these federal agency changes.  

The [federal agency update script](src/registrar/management/commands/populate_federal_agency_initials_and_fceb.py) was not run since the updates to the DB were done manually.
