### ISSUE TITLE
Content: Standardize HTML Page Titles

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#786]
### Issue Description
There are inconsistencies in how HTML page titles are written. 

Follow @kristinacyin's document by using her commented suggestions as a instructions on how to adjust our html page titles on manage.get.gov 

### Acceptance Criteria

- [ ] change the html page titles for manage.get.gov (including admin) by using [this document](https://docs.google.com/document/d/1Nk92LNq0pbPDS0EOjIsIcDEiP2da0Q5j7HoJF7l3xqo/edit#heading=h.hrnpd9cy4be
). All manage.get.gov titles with Word document Suggestions are the ones that need to be changed. **Ignore all the ones for audit logs**

out of scope: changing routes or get.gov titles. 

### Additional Context (optional)

[Discussion on Slack thread](https://cisa-corp.slack.com/archives/C06ES686Q2E/p1706821760593799) about changing tab titles to start with more specific information to generic & maybe removing unneeded information

> I'm wondering if we should go from specific > general in the order of things. For example:
Should  Request a .gov | Review and submit your domain request | .gov Registrar be Review and submit your domain request | Request a .gov | .gov Registrar? -Michelle

> I'm also wondering if we even need the "Request a .gov" part of this. -Michelle

> I'm gonna throw out a curveball.. what about ".Gov domain request | page title" remove "| .gov Registrar" altogether? -Gaby

### Issue Links
Relates to: https://github.com/cisagov/get.gov/issues/299
Related to #1385 ???

**Comment by PaulKuykendall** [comment]
@Katherine-Osos - is this pertaining to beta.get.gov or registrar?

**Comment by h-m-f-t** [comment]
@Katherine-Osos, has this been subsumed into the larger content review work? https://github.com/cisagov/manage.get.gov/issues?q=is%3Aissue+is%3Aopen+review+label%3Acontent

@michelle-rago filed a [targeted example](https://github.com/cisagov/manage.get.gov/issues/1385) to fix, too.

**Comment by Katherine-Osos** [comment]
@h-m-f-t For the most part, yes. However, we have multiple people reviewing the content so there's still a chance for inconsistencies in approach. We also need to document the standard in our content guide.

I think we should keep this ticket to do one final pass thru after the content review is completed. But it should be fairly quick.

**Comment by kristinacyin** [comment]
Ran into issues with my sandbox - will delete branch, pull from main, and redo

**Comment by vickyszuchin** [comment]
Added "dev" label: during pre-sprint planning, the decision from the leads were to assign the remaining work to the dev team. Slotted remaining work for sprint 45.

**Comment by abroddrick** [comment]
In hindsight @vickyszuchin I should have realized this needs a bit of refinement before we switched it to dev. I realize this requires a content decision as well as documentation for that content decision, @kristinacyin is that part done? Is the decision just to do "Gov domain request | page title"? This was my assumption but I realized that was based on the PR not on what is documented here.

I temporarily moved this to sprint 46 since there is an outstanding question. cc @Katherine-Osos

**Comment by vickyszuchin** [comment]
Added "refinement" label, see comment from Alysia on 5/6.

**Comment by kristinacyin** [comment]
I finally finished updating this doc: https://docs.google.com/document/d/1Nk92LNq0pbPDS0EOjIsIcDEiP2da0Q5j7HoJF7l3xqo/edit?usp=sharing

The suggestions that haven't been accepted yet are changes that need to be implemented. 

There is a current PR for get.gov changes: https://github.com/cisagov/get.gov/pull/293

There is no current PR for manage.get.gov changes.

**Comment by abroddrick** [comment]
@kristinacyin am I understanding correctly that this document is meant to show the actual html page titles we want, and thus that part is decided and now we just need to update them in the code, correct?

**Comment by kristinacyin** [comment]
@abroddrick 

1. Only suggestions in the doc need to paid attention to, everything else is what already exists/have already been changed. The suggestions are the changes we want and have already been decided on. 
2.  Yes, changes in the doc are included in the ticket, but can be split to another ticket if it makes more sense to do so.

**Comment by abroddrick** [comment]
Thanks @kristinacyin that clarifies things! I will make it clear the scope is just the html page titles not the routes. Kristina, I am finding it hard to use the suggestions. I can't click a suggestion and have it take to that spot, so I have to scroll through the document and the coloration is kind of hard to tell what's a suggestion because it switches colors based on what was changed. I would not recommend using this format going forward as it's hard for me to actually see the scope of the changes and it will be difficult for someone to make sure they completed everything.

**Comment by abroddrick** [comment]
@vickyszuchin can we get a ticket for the get.gov portion and any routes that need to be adjusted
